- name: Generar script de creacion de System Properties
  ansible.builtin.template:
    src: create_system_properties.sh.j2
    dest: "{{ gf_download_dir }}/create_system_properties.sh"
    mode: '0755'
  tags: create        

- name: Ejecutar script de creacion de System Properties
  ansible.builtin.shell: 
    cmd: "{{ gf_download_dir }}/create_system_properties.sh"
  tags: create        