- name: Generar script de creacion de Instancias para GlassFish
  ansible.builtin.template:
    src: create_instance.sh.j2
    dest: "{{ gf_download_dir }}/create_instance.sh"
    mode: '0755'
  tags: create    

- name: Ejecutar script de creacion de Instancias
  ansible.builtin.shell: 
    cmd: "{{ gf_download_dir }}/create_instance.sh"
  tags: create        