- name: Generar script de creacion de JDBC Pools para GlassFish
  ansible.builtin.template:
    src: create_jdbc_connection_pools.sh.j2
    dest: "{{ gf_download_dir }}/create_jdbc_connection_pools.sh"
    mode: '0755'
  tags: create        
        
- name: Ejecutar script de creacion de JDBC Pools
  ansible.builtin.shell: 
    cmd: "{{ gf_download_dir }}/create_jdbc_connection_pools.sh"
  tags: create        