# tasks/create_das_password.yml

- name: Enviar DAS New Pass
  ansible.builtin.template:
    src: das_new_password.j2
    dest: "{{ gf_new_password_dir }}"
    mode: '0755'
  tags: create    

- name: Enviar DAS Pass definido en variables
  ansible.builtin.template:
    src: das_password.j2
    dest: "{{ gf_password_dir }}"
    mode: '0755'    
  tags: create    

- name: Enviar Script de Creacion de DAS Pass
  ansible.builtin.template:
    src: create_das_password.sh.j2
    dest: "{{ gf_download_dir }}/create_das_password.sh"
    mode: '0755'
  tags: create    
        
- name: Ejecutar Script de Creacion de DAS Pass
  ansible.builtin.shell: 
    cmd: "{{ gf_download_dir }}/create_das_password.sh"
  tags: create    

  #