- name: Generar script de reinicio de Domain - [Test GF]
  ansible.builtin.template:
    src: restart_domain.sh.j2
    dest: "{{ gf_download_dir }}/restart_domain.sh"
    mode: '0755'
  tags:
    - create
    - install     

- name: Ejecutar script de reinicio de Domain - [Test GF]
  ansible.builtin.shell: 
    cmd: "{{ gf_download_dir }}/restart_domain.sh"
  tags:
    - create
    - install