- name: Kill process glassfish
  shell: "sudo pkill -u glassfish"
  ignore_errors: true
  become: true
  tags: gf_uninstall

- name: Eliminar Glassfish
  file:
    path: "{{ glassfish_home }}"
    state: absent
  become: true
  ignore_errors: true
  tags: gf_uninstall